apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: personal-website
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy  
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ3Bhc3M= 
  MONGODB_URI: bW9uZ29kYjovL21vbmdvdXNlcjptb25ncGFzc0Btb25nb2RiOjI3MDE3L3BlcnNvbmFsd2Vic2l0ZT9hdXRoU291cmNlPWFkbWlu
  ADMIN_PASS: YWRtaW5wYXNzMTIz  
  JWT_SECRET: and0LXNlY3JldC1rZXktY2hhbmdlLW1lLXRvLXNvbWV0aGluZy1zZWN1cmU= 
  GITHUB_TOKEN: Z2l0aHViX3BhdF94eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA==  
  RESEND_API_KEY: cmVfc3h4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA== 
